# The app's name, which must be unique within the project.
name: 'maxencetasse'

# The language and version for your app.
type: 'php:8.0'

# The size of the app's persistent disk (in MB).
disk: 512

relationships:
    database: "database1:mysql"

# The app's configuration when it's exposed to the web.
web:
    locations:
        '/':
            # The public directory relative to the app root.
            root: 'public'
            # Forward resources to the app.
            passthru: true
            # What files to use when serving a directory.
            index: ["index.html"]
            # Allow files even without specified rules.
            allow: true